name: 'pr-markdownlint'

on:
  pull_request:
    paths: ['**/*.md']

permissions:
  contents: read
  pull-requests: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - run: pnpm install
      - run: npx markdownlint-cli "**/*.md" --fix
      - uses: AnnaBeiyan/suggest-changes@c1b9c457171e9f967e9cd9b9714738b004dd41b2
        with:
          comment: 'Please commit the suggested changes from markdownlint.'
          event: 'COMMENT'